import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "./context/ThemContext";
// @ts-expect-error Next.js handles this global CSS side-effect import.
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-slate-50 text-slate-900 transition-colors duration-300 dark:bg-slate-950 dark:text-white`}
      >
        <ThemeProvider>
          <Navbar />

          <main className="min-h-screen pt-24">{children}</main>

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
